// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvebvlbyzxlpmygvbuxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2ZWJ2bGJ5enhscG15Z3ZidXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODY1NDksImV4cCI6MjA2ODA2MjU0OX0.sVkq2OcdI-gc1j-8neF4T3YyQy_25hkweqaU2mZxJUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});